### ISSUE TITLE
Package Request: Mpv-Discord-RPC

### ISSUE THREAD

**Issue by Tanish2002** [fortuneteller2k/nixpkgs-f2k#12]
Not sure if you address package requests but if you do then can you please package mpv discord rpc: https://github.com/cniw/mpv-discordRPC

I just want rich presence for mpv.

**Comment by moni-dz** [comment]
https://github.com/fortuneteller2k/nixpkgs-f2k/commit/de258331f1bf67d7bc8766a2b7a2f818cbcbeb90

**Comment by Tanish2002** [comment]
Thanks!

**Comment by Tanish2002** [comment]
@fortuneteller2k doesn't seem to be working
mpv config is like this(using home-manager)
```nix
  programs = {
    mpv = {
      enable = true;
      package =
        pkgs.wrapMpv (pkgs.mpv-unwrapped.override { sixelSupport = true; }) {
          youtubeSupport = true;
          scripts = [ pkgs.mpv-discord-script ];
        };
      config = {
        input-ipc-server = "/tmp/mpvsocket";
        sub-auto = "all";
      };
    };
  };
```
The error I am getting is this:
![image](https://user-images.githubusercontent.com/55488165/173242160-f47369ab-f3b4-4643-86f6-1d96979cb226.png)

**Comment by moni-dz** [comment]
should be good now

**Comment by Tanish2002** [comment]
seemed to install fine but doesn't seem to working i.e I don't get any rich presence in discord...
here is how am managing the config
```nix
  xdg.configFile = {
    "discord.conf" = {
      text = ''
        binary_path=${pkgs.mpv-discord}/bin/mpv-discord
      '';
      target = "mpv/script-opts/discord.conf";
    };
};
```
Mpv config is same as previous message.

**Comment by Tanish2002** [comment]
or not my bad. this seems to be related to my config.
The script I am using to play songs uses a different version of mpv
