### ISSUE TITLE
non flake config problems

### ISSUE THREAD

**Issue by paulhersch** [fortuneteller2k/nixpkgs-f2k#13]
Hi, after adjusting to your new flake structure i get the following error with my non-flake config:

```
trace: warning: nixpkgs-f2k.overlay is deprecated, use nixpkgs-f2k.overlays.default instead
error: value is a function while a set was expected
```
relevant code:
```
        nixpkgs.overlays = [
                (builtins.getFlake "github:fortuneteller2k/nixpkgs-f2k").overlay.default
        ];
```

Is there something i can do? I dont know how flakes work (they are enabled tho) so i am kinda stuck here.

**Comment by moni-dz** [comment]
It's `overlays` not `overlay`.

**Comment by paulhersch** [comment]
I am certified stupid :+1:
