### ISSUE TITLE
I am getting make error for awesomewm

### ISSUE THREAD

**Issue by mobsenpai** [fortuneteller2k/nixpkgs-f2k#25]
![awesome-error](https://github.com/fortuneteller2k/nixpkgs-f2k/assets/92603465/1360b539-ec64-42d7-8708-178889d31d42)

How I have nixos setup
[dotfiles](https://github.com/MobSenpai/dotfiles)
[awesome module](https://github.com/MobSenpai/dotfiles/blob/main/modules/nixos/awesome.nix)
[overlay](https://github.com/MobSenpai/dotfiles/blob/main/overlays/default.nix)

**Comment by moni-dz** [comment]
the full log would be more helpful

**Comment by mobsenpai** [comment]
the log was too long so I have shared the mega link
[logs](https://mega.nz/file/97AFDCIQ#4WuiIjXfCRUkf6yn1O34N1AuSOCKaFBus1IGtudOcfk)

**Comment by moni-dz** [comment]
this repo has `awesome-luajit-git`

**Comment by MobSenpai** [comment]
Oh yeah I now am using your luajit version it was awesome-git before
![2023-06-20_22-59](https://github.com/fortuneteller2k/nixpkgs-f2k/assets/92603465/4f42152b-4a17-4a53-94ec-f1501519b27c)
Wow It built.
Sorry for taking time but why the igi module shows this when awesome -v, I've seen that it is a common thing on nixos and is normal is that true?

**Comment by MobSenpai** [comment]
Also can you check the config here, I have done the same as rxyhn/yuki. Is it correct or overdone or any good changes ??
{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.xserver.windowManager.awesome;

  # reinventing the wheel of the default awesomewm module
  getLuaPath = lib: dir: "${lib}/${dir}/lua/${pkgs.luajit.luaversion}";
  makeSearchPath = lib.concatMapStrings (
    path:
      " --search "
      + (getLuaPath path "share")
      + " --search "
      + (getLuaPath path "lib")
  );

  luaModules = lib.attrValues {
    inherit
      (pkgs.luajitPackages)
      lgi
      # ldbus
      
      # luadbi-mysql
      
      # luaposix
      
      ;
  };
in {
  options = {
    services.xserver.windowManager.awesome = {
      enable = mkEnableOption (lib.mdDoc "Awesome window manager");
    };
  };

  config = mkIf cfg.enable {
    services.xserver = {
      enable = true;
      exportConfiguration = true;

      displayManager = {
        defaultSession = "none+awesome";
        lightdm.enable = true;
      };

      windowManager.session =
        singleton
        {
          name = "awesome";
          start = ''
            ${pkgs.awesome-luajit-git}/bin/awesome ${makeSearchPath luaModules} &
            waitPID=$!
          '';
        };
    };

    environment.systemPackages = lib.attrValues {
      inherit
        (pkgs)
        awesome-luajit-git
        feh
        pcmanfm
        tmux
        xclip
        xss-lock
        ;
    };
  };
}
# Note: this only installs stuff so no need to comment other wm's when installing another wm's

Also if you could check my nix config, and give it a heads up please

**Comment by moni-dz** [comment]
something similar to https://git.gemia.net/paul.s/nixdots/-/blob/main/modules/x11/awesome.nix where you modify the search path

**Comment by MobSenpai** [comment]
> something similar to https://git.gemia.net/paul.s/nixdots/-/blob/main/modules/x11/awesome.nix where you modify the search path

Yeah so people use this, but for me even after using this I have the lgi not found thing, then isn't it better to keep it simple and traditional, is what I am asking.

**Comment by moni-dz** [comment]
idk man this is well beyond the scope of what was originally the issue, that's really not up to me to decide how you use it

**Comment by mobsenpai** [comment]
Oh okay. Thank you
