### ISSUE TITLE
Phocus hash mismatch

### ISSUE THREAD

**Issue by Octelly** [fortuneteller2k/nixpkgs-f2k#26]
Blame indicates the latest commit to be the culprit: https://github.com/moni-dz/nixpkgs-f2k/commit/116b8bf06dc8d2a416fee0ce6d5e084118e67b4a

![Screenshot_20240806_133225](https://github.com/user-attachments/assets/bfcab446-714d-44b4-97ce-5a535c4a5949)

**Comment by moni-dz** [comment]
fixed for now, i'll investigate why it's doing this for the 2nd time
